linters-settings:
  govet:
    enable:
      - shadow
  # gocyclo is deprecated in favor of cyclop, but keeping for now if preferred
  gocyclo:
    min-complexity: 15
  # maligned is deprecated, replacement is govet 'fieldalignment'
  # dupl is archived
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: "github.com/sirupsen/logrus"
            desc: "logging is allowed only by logutils.Log"
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/junevm/msifancontrol
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 5m
