# .goreleaser.yaml
# Documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/fan/main.go
    binary: msifancontrol
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    # this name template makes the result be named <project>_<version>_<os>_<arch>
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

brews:
  - name: msifancontrol
    repository:
      owner: junevm
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/junevm/msifancontrol"
    description: "🪭 fan control tui for msi laptops using linux"
    license: "MIT"
    install: |
      bin.install "msifancontrol"
