version: 3

tasks:
  run:
    desc: Run MSIFanControl
    silent: true
    cmds:
      - chmod +x install.sh
      - ./install.sh
      - export GI_TYPELIB_PATH=/usr/lib64/girepository-1.0:$GI_TYPELIB_PATH && sudo -E ./.venv/bin/python3 src/main.py
