version: 3

# This Taskfile automates the build and run process.
# It's like a "Makefile" but easier to read.
# You need to install 'task' (https://taskfile.dev) to use it.

tasks:
  # The default task runs when you just type 'task'.
  default:
    cmds:
      - task -l

  # 'build' compiles the Go code into an executable binary.
  build:
    desc: Build the application
    cmds:
      - go mod tidy
      - mkdir -p bin # Create the output directory if it doesn't exist.
      - go build -o bin/fan cmd/fan/main.go # Compile the code.

  # 'run' executes the app directly using 'go run'.
  run:
    desc: Run MSIFanControl (Auto-setup)
    cmds:
      - go run ./cmd/fan # Run the code directly. It will prompt for sudo if needed.

  # 'install' installs the binary to the system.
  install:
    desc: Install 'fan' to /usr/local/bin
    deps: [build]
    cmds:
      - sudo cp bin/fan /usr/local/bin/fan
      - echo "✅ Installed! You can now run 'sudo fan'"

  # 'clean' removes the built binary to start fresh.
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin
